-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 11:02:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mariabonita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mariabonita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mariabonita` DEFAULT CHARACTER SET utf8 ;
USE `mariabonita` ;

-- -----------------------------------------------------
-- Table `mariabonita`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mariabonita`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `idclientes_UNIQUE` (`idclientes` ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mariabonita`.`pratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mariabonita`.`pratos` (
  `idpratos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `diaSemana` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`preco`),
  UNIQUE INDEX `idpratos_UNIQUE` (`idpratos` ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mariabonita`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mariabonita`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `pratos_preco` VARCHAR(45) NOT NULL,
  `clientes_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpedidos`),
  INDEX `fk_pedidos_pratos1_idx` (`pratos_preco`),
  INDEX `fk_pedidos_clientes1_idx` (`clientes_usuario`),
  CONSTRAINT `fk_pedidos_pratos1`
    FOREIGN KEY (`pratos_preco`)
    REFERENCES `mariabonita`.`pratos` (`preco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_usuario`)
    REFERENCES `mariabonita`.`clientes` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
